// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmASNjKxUDbFnzX3OquNfVpxfBvZTFbTY',
    appId: '1:1058424752673:web:0171d5e3623c00aef3f160',
    messagingSenderId: '1058424752673',
    projectId: 'versal-9f41b',
    authDomain: 'versal-9f41b.firebaseapp.com',
    storageBucket: 'versal-9f41b.firebasestorage.app',
    measurementId: 'G-FX918VG8VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_InzIGQvQ2htgt0mizJdt4p2A3Ane4KI',
    appId: '1:1058424752673:android:2582de8cc4cb1607f3f160',
    messagingSenderId: '1058424752673',
    projectId: 'versal-9f41b',
    storageBucket: 'versal-9f41b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPvOZbWf23fAw10lQUSuGAiPFUs9KTj8',
    appId: '1:1058424752673:ios:0d0d47bd821a4f75f3f160',
    messagingSenderId: '1058424752673',
    projectId: 'versal-9f41b',
    storageBucket: 'versal-9f41b.firebasestorage.app',
    iosBundleId: 'com.barber.versal',
  );
}
