// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo331U_XLXPXr5bqc1ye21apuUKsb07hM',
    appId: '1:564577343588:web:d26d94340584bb9ea6a771',
    messagingSenderId: '564577343588',
    projectId: 'versalbarbershop',
    authDomain: 'versalbarbershop.firebaseapp.com',
    databaseURL: 'https://versalbarbershop-default-rtdb.firebaseio.com',
    storageBucket: 'versalbarbershop.firebasestorage.app',
    measurementId: 'G-3FD4FR1KJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-dTpUlYjmRLnrIYdGMnWRdJ40pUO2Rdw',
    appId: '1:564577343588:android:5d7b9b3257d59a76a6a771',
    messagingSenderId: '564577343588',
    projectId: 'versalbarbershop',
    databaseURL: 'https://versalbarbershop-default-rtdb.firebaseio.com',
    storageBucket: 'versalbarbershop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOiAhIDaMvQybFGlLBV1H_e1Vmw9ikR0',
    appId: '1:564577343588:ios:2e7001ef3cd77154a6a771',
    messagingSenderId: '564577343588',
    projectId: 'versalbarbershop',
    databaseURL: 'https://versalbarbershop-default-rtdb.firebaseio.com',
    storageBucket: 'versalbarbershop.firebasestorage.app',
    iosBundleId: 'com.example.versal',
  );
}
